// ui/src/components/Canvas.tsx
import React from 'react';
import './Canvas.css';
import * as workflow from '../workflow';
import { sortByKey } from '../utils';
import { Step } from './Step';
import { Port } from './Port';
import { Connection } from './Connection';

interface CanvasProps {
  workflow: workflow.Workflow;

  onStepAdd: () => void;
  onStepRemove: () => void;
  onStepMove: () => void;
  onSetInputParameter: () => void;
  onSetConnection: () => void;
  onRemoveConnection: () => void;
}

interface CanvasState {
  // Port positions reported from Step, used to position Port and Connection
  ports: Map<string, [number, number]>;
}

export class Canvas extends React.PureComponent<CanvasProps, CanvasState> {
  constructor(props: CanvasProps) {
    super(props);

    this.state = { ports: new Map() };

    this.setPort = this.setPort.bind(this);
    this.moveStep = this.moveStep.bind(this);
    this.removeStep = this.removeStep.bind(this);
    this.setInputParameter = this.setInputParameter.bind(this);
  }

  setPort(
    stepId: string,
    type: workflow.PortType,
    name: string,
    position: [number, number]
  ) {
    this.setState(prevState => {
      const ports = new Map(prevState.ports);
      ports.set(`${stepId}.${type}.${name}`, position);
      return { ports, ...prevState };
    });
  }

  moveStep() {}

  removeStep() {}

  setInputParameter() {}

  computeConnections() {
    // Pre-compute port information
    const stepOutputIndex: Map<string, Map<string, number>> = new Map();
    const stepInputIndex: Map<string, Map<string, number>> = new Map();
    this.props.workflow.steps.forEach(step => {
      // Index outputs
      {
        let count = 0;
        const outputIndexes = new Map();
        for (const output of step.outputs) {
          outputIndexes.set(output, count++);
        }
        stepOutputIndex.set(step.id, outputIndexes);
      }

      // Index inputs
      {
        let count = 0;
        const inputs = Object.entries(step.inputs);
        sortByKey(inputs, o => o[0]);
        const inputIndexes = new Map();
        for (const [inputName] of inputs) {
          inputIndexes.set(inputName, count++);
        }
        stepInputIndex.set(step.id, inputIndexes);
      }
    });

    // For each step, for each of its input, for each of its connection
    const connections: Array<{}> = [];
    this.props.workflow.steps.forEach(step => {
      step.inputs.forEach((inputArray, inputName) => {
        inputArray.forEach(input => {
          if (input.type === 'connection') {
            // Get position of source output port
            const skey = `${input.step_id}.output.${input.output_name}`;
            const spos = this.state.ports.get(skey);
            if (!spos) {
              return;
            }

            // Get position of destination input port
            const dkey = `${step.id}.input.${inputName}`;
            const dpos = this.state.ports.get(dkey);
            if (!dpos) {
              return;
            }

            // Add connection to array
            connections.push({
              key: `${skey}.${dkey}`,
              source_step_id: input.step_id,
              source_output_name: input.output_name,
              dest_step_id: step.id,
              dest_input_name: inputName,
              source: spos,
              dest: dpos,
            });
          }
        });
      });
    });
    return connections;
  }

  renderSteps() {
    const steps: JSX.Element[] = [];
    this.props.workflow.steps.forEach(step => {
      steps.push(
        <Step
          key={step.id}
          step={step}
          onSetPort={(
            type: workflow.PortType,
            name: string,
            position: [number, number]
          ) => this.setPort(step.id, type, name, position)}
          onMove={this.moveStep}
          onRemove={this.removeStep}
          onSetInputParameter={this.setInputParameter}
        />
      );
    });
    return steps;
  }

  renderPorts() {
    const ports: JSX.Element[] = [];
    this.state.ports.forEach((position, key) => {
      ports.push(<Port key={key} position={position} />);
    });
    return ports;
  }

  renderConnections() {
    const connectionsList = this.computeConnections();
    const connections: JSX.Element[] = [];
    connectionsList.forEach(connection => {
      connections.push(<Connection />);
    });
    return connections;
  }

  render() {
    return (
      <>
        <div className="canvas">{this.renderSteps()}</div>
        <svg className="canvas ports">{this.renderPorts()}</svg>
        <svg className="canvas connections">{this.renderConnections()}</svg>
      </>
    );
  }
}

// ui/src/components/Canvas.vue
<template>
  <div>
    <div class="canvas">
      <Step
        v-for="(step, name) in workflow.steps" :key="name"
        :step="step" :name="name"
        v-on:setport="setPort"
        v-on:stepmove="moveStep"
        v-on:remove="removeStep(name)"
        />
    </div>
    <svg class="canvas ports">
      <Port
        v-for="port in this.ports" :key="port.name"
        :port="port"
        />
    </svg>
    <svg class="canvas connections">
      <Connection
        v-for="connection of connections" :key="connection.key"
        :connection="connection.data"
        />
    </svg>
  </div>
</template>

<script>
import Step from './Step.vue'
import Port from './Port.vue'
import Connection from './Connection.vue'
import { sortByKey } from '../utils.js'

export default {
  name: 'Canvas',
  props: ['workflow'],
  data: function() {
    return {
      ports: {},
    };
  },
  computed: {
    connections: function() {
      // Pre-compute port information
      let step_output_index = {};
      let step_output_count = {};
      let step_input_index = {};
      for(let step_id in this.workflow.steps) {
        let step = this.workflow.steps[step_id];

        // Index outputs
        {
          let count = 0;
          step_output_index[step_id] = {};
          for(let output of step.outputs) {
            step_output_index[step_id][output] = count++;
          }
          step_output_count[step_id] = count;
        }

        // Index inputs
        {
          let count = 0;
          step_input_index[step_id] = {};
          let inputs = Object.entries(step.inputs);
          sortByKey(inputs, function(o) { return o[0]; });
          for(let [input_name,] of inputs) {
            step_input_index[step_id][input_name] = count++;
          }
        }
      }

      // For each step, for each of its input, for each of its connection
      let connections = [];
      for(let step_id in this.workflow.steps) {
        let step = this.workflow.steps[step_id];
        for(let input_name in step.inputs) {
          let input_array = step.inputs[input_name];
          for(let source of input_array) {
            if(!(typeof source == "string")) {
              // Compute position of source output port
              let sx = 0, sy = 0;
              let skey = `${source.step}.out.${source.output}`;
              if(skey in this.ports) {
                [sx, sy] = this.ports[skey].position;
              }

              // Compute position of destination input port
              let dx = 0, dy = 0;
              let dkey = `${step_id}.in.${input_name}`;
              if(dkey in this.ports) {
                [dx, dy] = this.ports[dkey].position;
              }

              // Add connection to array
              connections.push({
                key: `${step_id}.${input_name}.${source.step}.${source.output}`,
                data: `M ${sx} ${sy} C ${sx + 40} ${sy} ${dx - 40} ${dy} ${dx} ${dy}`,
              });
            }
          }
        }
      }
      return connections;
    },
  },
  methods: {
    setPort: function(port) {
      if(port.position !== undefined) {
        this.$set(this.ports, port.name, port);
      } else {
        this.$delete(this.ports, port.name);
      }
    },
    moveStep: function(e) {
      this.$emit('stepmove', e);
    },
    removeStep: function(name) {
      this.$emit('stepremove', name);
    },
  },
  components: {
    Step,
    Port,
    Connection,
  },
}
</script>

<style scoped>
div.canvas {
  position: absolute;
  width: 100%;
  height: 100%;
  background-color: #eee;
}

svg.canvas {
  position: fixed;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
}

svg.ports {
  z-index: 14;
  pointer-events: none;
}

svg.connections {
  z-index: 5;
}
</style>
