// ui/src/components/Connection.vue
<template>
  <path :d="path" class="connection"/>
</template>

<script>
export default {
  name: 'Connection',
  props: ['source', 'dest'],
  computed: {
    path: function() {
      let [sx, sy] = this.source;
      let [dx, dy] = this.dest;
      return `M ${sx} ${sy} C ${sx + 40} ${sy} ${dx - 40} ${dy} ${dx} ${dy}`;
    },
  },
}
</script>

<style scoped>
path.connection {
  stroke: black;
  fill: none;
  z-index: 10;
}
</style>

// ui/src/components/Connection.tsx
import React from 'react';
import './Connection.css';

interface ConnectionProps {
  source: [number, number];
  dest: [number, number];
}

export class Connection extends React.PureComponent<ConnectionProps> {
  render() {
    const [sx, sy] = this.props.source;
    const [dx, dy] = this.props.dest;
    const path = `M ${sx} ${sy} C ${sx + 40} ${sy} ${dx - 40} ${dy} ${dx} ${dy}`;
    return (
      <path d={path} className="connection" />
    );
  }
}
