// ui/src/components/Step.tsx
import React from 'react';
import './Step.css';
import { sortByKey } from '../utils';
import * as workflow from '../workflow';

interface StepProps {
  step: workflow.Step;
  setPort: (
    type: workflow.PortType,
    name: string,
    position: [number, number]
  ) => void;
  unsetPort: (type: workflow.PortType, name: string) => void;
  onMove: (position: [number, number]) => void;
  onRemove: () => void;
  onSetInputParameter: (name: string, value: string) => void;
}

interface StepState {
  position?: [number, number];
}

export class Step extends React.PureComponent<StepProps, StepState> {
  outputsRef: React.RefObject<HTMLTableElement>;
  inputsRef: React.RefObject<HTMLTableElement>;

  offset?: [number, number];

  constructor(props: StepProps) {
    super(props);
    this.state = {};

    this.outputsRef = React.createRef();
    this.inputsRef = React.createRef();

    this.onMouseDown = this.onMouseDown.bind(this);
    this.onMouseUp = this.onMouseUp.bind(this);
    this.onMouseMove = this.onMouseMove.bind(this);
  }

  getPosition(): [number, number] {
    return this.state.position || this.props.step.position;
  }

  onMouseDown(e: React.MouseEvent) {
    // Click on the Step itself, not children
    if (e.target !== e.currentTarget) {
      return;
    }
    // Left button only
    if (e.button !== 0) {
      return;
    }
    e.preventDefault();

    document.addEventListener('mouseup', this.onMouseUp);
    document.addEventListener('mousemove', this.onMouseMove);
    this.offset = [
      this.props.step.position[0] - e.clientX,
      this.props.step.position[1] - e.clientY,
    ];
  }

  onMouseUp(e: MouseEvent) {
    e.preventDefault();
    document.removeEventListener('mouseup', this.onMouseUp);
    document.removeEventListener('mousemove', this.onMouseMove);
    if (this.offset) {
      this.props.onMove([
        e.clientX + this.offset[0],
        e.clientY + this.offset[1],
      ]);
      this.offset = undefined;
    }
  }

  onMouseMove(e: MouseEvent) {
    e.preventDefault();
    if (this.offset) {
      this.setState({
        position: [e.clientX + this.offset[0], e.clientY + this.offset[1]],
      });
    }
  }

  changeInput(name: string, e: React.ChangeEvent<HTMLInputElement>) {
    this.props.onSetInputParameter(name, e.target.value);
  }

  componentDidMount() {
    this.sendPortLocations();
  }

  componentDidUpdate(prevProps: StepProps) {
    this.sendPortLocations(prevProps.step);
  }

  componentWillUnmount() {
    this.props.step.outputs.forEach(output => {
      this.props.unsetPort('output', output);
    });
    this.props.step.inputs.forEach((_, input) => {
      this.props.unsetPort('input', input);
    });
  }

  sendPortLocations(prevStep?: workflow.Step) {
    // Send output port information
    if (this.outputsRef.current) {
      const prevOutputs = new Set(prevStep ? prevStep.outputs : []);
      const outputs = this.getOutputs();
      this.outputsRef.current
        .querySelectorAll('.outputs tr')
        .forEach((row, i) => {
          const rect = row.getBoundingClientRect();
          this.props.setPort('output', outputs[i], [
            rect.right + 6,
            (rect.top + rect.bottom) / 2,
          ]);
          prevOutputs.delete(outputs[i]);
        });
      prevOutputs.forEach(output => {
        this.props.unsetPort('output', output);
      });
    }

    // Send input port information
    if (this.inputsRef.current) {
      const prevInputs = new Set(prevStep ? prevStep.inputs.keys() : []);
      const inputs = this.getInputs();
      this.inputsRef.current
        .querySelectorAll('.inputs tr')
        .forEach((row, i) => {
          const rect = row.getBoundingClientRect();
          this.props.setPort('input', inputs[i][0], [
            rect.left - 6,
            (rect.top + rect.bottom) / 2,
          ]);
          prevInputs.delete(inputs[i][0]);
        });
      prevInputs.forEach(input => {
        this.props.unsetPort('input', input);
      });
    }
  }

  getOutputs() {
    const outputs = this.props.step.outputs.slice();
    outputs.sort();
    return outputs;
  }

  getInputs() {
    const inputEntries = Array.from(this.props.step.inputs.entries());
    const inputs: Array<[string, string | undefined]> = inputEntries.map(
      ([name, values]) => {
        if (values.length === 0) {
          return [name, ''];
        } else if (values[0].type !== 'constant') {
          return [name, undefined];
        } else {
          return [name, values[0].value];
        }
      }
    );
    sortByKey(inputs, o => o[0]);
    return inputs;
  }

  render() {
    const style = {
      left: this.getPosition()[0] + 'px',
      top: this.getPosition()[1] + 'px',
    };

    return (
      <div className="step" style={style} onMouseDown={this.onMouseDown}>
        <button className="close" onClick={this.props.onRemove}>
          [x]
        </button>
        <h2>{this.props.step.component.type}</h2>
        <table className="outputs" ref={this.outputsRef}>
          <tbody>
            {this.getOutputs().map(output => (
              <tr key={output}>
                <td>???</td>
                <td>{output}</td>
              </tr>
            ))}
          </tbody>
        </table>
        <table className="inputs" ref={this.inputsRef}>
          <tbody>
            {this.getInputs().map(([name, value]) => (
              <tr key={name}>
                <td>{name}</td>
                <td>
                  {value !== undefined && (
                    <input
                      type="text"
                      defaultValue={value}
                      onChange={event => this.changeInput(name, event)}
                    />
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  }
}

// ui/src/components/Step.vue
<template>
  <div
    class="step" :style=style
    v-on:mousedown.left.self.prevent="mousedown"
    >
    <a class="close" v-on:click.self.prevent="remove">[x]</a>
    <h2>{{step.component.type}}</h2>
    <table class="outputs">
      <tr v-for="output of outputs" :key="output">
        <td>???</td>
        <td>{{output}}</td>
      </tr>
    </table>
    <table class="inputs">
      <tr v-for="input of inputs" :key="input[0]">
        <td>{{input[0]}}</td>
        <td>
          <input
            type="text" v-if="input[1] !== null"
            :value="input[1]"
            v-on:change="changeInput(input[0], $event)"
            />
        </td>
      </tr>
    </table>
  </div>
</template>

<script>
import { sortByKey } from '../utils.js'

export default {
  name: 'Step',
  props: ['step'],
  computed: {
    inputs: function() {
      let entries = Object.entries(this.step.inputs);
      sortByKey(entries, function(o) { return o[0]; });
      for(let i = 0; i < entries.length; ++i) {
        if(entries[i][1].length == 0) {
          entries[i][1] = "";
        } else if(typeof entries[i][1][0] != "string") {
          entries[i][1] = null;
        }
      }
      return entries;
    },
    outputs: function() {
      let outputs = this.step.outputs.slice();
      outputs.sort();
      return outputs;
    },
    style: function() {
      return `left: ${this.step.position[0]}px; top: ${this.step.position[1]}px;`;
    },
  },
  methods: {
    sendUpdate: function() {
      // Send output port information
      let output_rows = this.$el.querySelectorAll(".outputs tr");
      for(let i = 0; i < output_rows.length; ++i) {
        let rect = output_rows[i].getBoundingClientRect();
        this.$emit(
          'setport',
          {
            key: `${this.step.id}.out.${this.step.outputs[i]}`,
            type: 'output',
            step_id: this.step.id,
            port_name: this.step.outputs[i],
            position: [rect.right + 6, (rect.top + rect.bottom) / 2],
          },
        );
      }

      // Send input port information
      let input_rows = this.$el.querySelectorAll(".inputs tr");
      for(let i = 0; i < input_rows.length; ++i) {
        let rect = input_rows[i].getBoundingClientRect();
        this.$emit(
          'setport',
          {
            key: `${this.step.id}.in.${this.inputs[i][0]}`,
            type: 'input',
            step_id: this.step.id,
            port_name: this.inputs[i][0],
            position: [rect.left - 6, (rect.top + rect.bottom) / 2],
          },
        );
      }
    },
    changeInput: function(input_name, event) {
      this.$emit(
        'setinputparameter',
        {
          step_id: this.step.id,
          input_name: input_name,
          value: event.target.value,
        },
      );
    },
    mousedown: function(event) {
      document.addEventListener('mouseup', this.mouseup);
      document.addEventListener('mousemove', this.mousemove);
      this.offset = [
        this.step.position[0] - event.clientX,
        this.step.position[1] - event.clientY,
      ];
    },
    mouseup: function() {
      document.removeEventListener('mouseup', this.mouseup);
      document.removeEventListener('mousemove', this.mousemove);
      this.$emit('stepmove', {step_id: this.step.id, position: this.step.position});
    },
    mousemove: function(event) {
      event.preventDefault();
      this.step.position = [
        event.clientX + this.offset[0],
        event.clientY + this.offset[1],
      ];
    },
    remove: function() {
      this.$emit("remove");
    },
  },
  mounted: function() {
    this.$nextTick(this.sendUpdate);
  },
  updated: function() {
    this.$nextTick(this.sendUpdate);
  },
  beforeDestroy: function() {
    // Remove event listeners
    document.removeEventListener('mousemove', this.mousemoved);
    document.removeEventListener('mouseup', this.mouseup);

    // Destroy output ports
    for(let output of this.step.outputs) {
      this.$emit(
        'setport',
        {
          key: `${this.step.id}.out.${output}`,
          position: undefined,
        },
      );
    }

    // Destroy input ports
    for(let input of this.inputs) {
      this.$emit(
        'setport',
        {
          key: `${this.step.id}.in.${input[0]}`,
          position: undefined,
        },
      );
    }
  },
}
</script>

<style scoped>
.step {
  position: absolute;
  width: 200px;
  border: 2px solid black;
  border-radius: 15px;
  padding: 6px;
  z-index: 10;
  background-color: white;
}

.step * {
  pointer-events: none;
}

.step h2 {
  text-align: center;
  margin: 0;
  height: 32px;
}

.step td {
  font-size: 0.85rem;
}

.step input {
  min-width: 0;
  width: 100%;
  box-sizing: border-box;
  pointer-events: auto;
}

.step table.inputs {
  margin-right: auto;
  padding: 0;
  border-collapse: collapse;
}

.step table.inputs tr, .step table.inputs td {
  padding: 0 2px 0 2px;
}

.step table.outputs {
  margin-left: auto;
  padding: 0;
  border-collapse: collapse;
}

.step table.outputs tr, .step table.outputs td {
  padding: 0 2px 0 2px;
}

a.close {
  position: absolute;
  right: 6px;
  top: 6px;
  pointer-events: auto;
}
</style>
